# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-20 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Iphone', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='Enviados',
        ),
    ]
